// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DGntsB1oXBUYbP5-QLbsxe2wv4-OxhU',
    appId: '1:973084844515:android:c5c08d3019cd2f343cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    storageBucket: 'snow-chat-f33a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wCzdDz5KF8mD3zid3yoNd49KZs1RpKI',
    appId: '1:973084844515:ios:68d729c268d3b1043cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    storageBucket: 'snow-chat-f33a4.appspot.com',
    androidClientId: '973084844515-gvpai5ujuket1np73m6ano5re72q1mno.apps.googleusercontent.com',
    iosClientId: '973084844515-2lktlg2225r4oqn767dr02r6rn21ojcm.apps.googleusercontent.com',
    iosBundleId: 'com.example.iceChat',
  );
}
