// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZ3R7E5UP4qNJmbSv-nA9dixL-jdxrK5I',
    appId: '1:973084844515:web:9428f6923e06a3933cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    authDomain: 'snow-chat-f33a4.firebaseapp.com',
    storageBucket: 'snow-chat-f33a4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_DGntsB1oXBUYbP5-QLbsxe2wv4-OxhU',
    appId: '1:973084844515:android:0b92758fd2f09d2d3cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    storageBucket: 'snow-chat-f33a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wCzdDz5KF8mD3zid3yoNd49KZs1RpKI',
    appId: '1:973084844515:ios:4b542f49024d44ad3cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    storageBucket: 'snow-chat-f33a4.appspot.com',
    androidClientId: '973084844515-gvpai5ujuket1np73m6ano5re72q1mno.apps.googleusercontent.com',
    iosClientId: '973084844515-bbrubli616si0tqpicqro28uro9sq7iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.snowChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wCzdDz5KF8mD3zid3yoNd49KZs1RpKI',
    appId: '1:973084844515:ios:4b542f49024d44ad3cc0d6',
    messagingSenderId: '973084844515',
    projectId: 'snow-chat-f33a4',
    storageBucket: 'snow-chat-f33a4.appspot.com',
    androidClientId: '973084844515-gvpai5ujuket1np73m6ano5re72q1mno.apps.googleusercontent.com',
    iosClientId: '973084844515-bbrubli616si0tqpicqro28uro9sq7iq.apps.googleusercontent.com',
    iosBundleId: 'com.example.snowChat',
  );
}
